# Generated by Django 4.2.6 on 2023-11-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=264)),
                ('movieyear', models.CharField(max_length=264)),
                ('movietime', models.TimeField()),
                ('movierating', models.CharField(max_length=264)),
                ('movieurl', models.URLField()),
                ('moviedirector', models.CharField(max_length=264)),
                ('directorurl', models.URLField()),
                ('topMovie', models.CharField(max_length=264)),
            ],
        ),
    ]
