# Generated by Django 4.2.6 on 2023-11-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingApp', '0002_movieinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='movietime',
            field=models.CharField(max_length=264),
        ),
    ]
